version: '3.8'

services:
  # Cơ sở dữ liệu MongoDB
  mongodb:
    image: mongo:latest
    container_name: docs4study-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - docs4study-network

  # Server là backend
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: docs4study-server
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-5001}:5001"
    env_file:
      - .env
      - ./server/.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGODB=${MONGO_URL}
    depends_on:
      - mongodb
    networks:
      - docs4study-network
    volumes:
      - ./server:/app
      - /app/node_modules

  #Client là frontend
  client:
    build:
      context: ./client
      dockerfile: dockerfile
      args:
        - CODESPACE_NAME=${CODESPACE_NAME}
    container_name: docs4study-client
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT:-80}:80"
    environment:
      - CODESPACE_NAME=${CODESPACE_NAME}
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - docs4study-network

networks:
  docs4study-network:
    driver: bridge

volumes:
  mongodb_data:
